config/routes.rb
Rails.application.routes.draw do
  resources :bugs, only: [:show]
  resources :commits, only: [:index]

  scope :module => 'search' do
    get '/search'  => :search, as: :search
  end
  
  root to: "commits#index"
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :commits
end

app/models/bug.rb
class Bug < ActiveRecord::Base
  has_one :commit
end

app/models/commit.rb
class Commit < ActiveRecord::Base
  belongs_to :bug
  belongs_to :author
  BUG_REGEX = /cr\s(?:#|number\s)?(\d+)/i
  scope :search_by_author, lambda { |author| where("authors.name LIKE '%#{author}%'").references(:authors) }
  scope :search_by_committed_at, lambda { |date| where("commits.committed_at LIKE '#{date}%'") }
  scope :search_by_commit_hash, lambda { |hash| where("commits.commit_hash LIKE '#{hash}%'") }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  def show
  end
end

app/controllers/commits_controller.rb
class CommitsController < ApplicationController
  def index
    @authors = Author.all
    commits = Commit.includes(:author).order(committed_at: :desc)
    @presenter = commits.map { |commit| CommitPresenter.new(commit) }
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  SEARCH_FILTERS = [:author, :committed_at, :commit_hash]
  
  def search
    @authors = Author.all
    commits = Commit.includes(:author).order(committed_at: :desc)
    SEARCH_FILTERS.each do |filter|
      commits = add_search_filter(commits, filter)
    end
    commits = [] if no_search_terms
    flash[:success] = "Found #{commits.count} results"
    @presenter = commits.map { |commit| CommitPresenter.new(commit) }
  end

  private

  def no_search_terms
    SEARCH_FILTERS.map { |filter| params[filter].blank? }.all? { |blank| blank == true }
  end

  def add_search_filter(relation, field)
    if params[field].present?
      relation.merge(Commit.send("search_by_#{field}",params[field]))
    else
      relation
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def html_safe(*args)
    output = "".html_safe
    args.each {|current_arg|
      output << current_arg.html_safe
    }
    output
  end

  def parse_flash(flash)
    hash = {}

    if flash[:error]
      hash[:message] = flash[:error]
      hash[:style] = 'alert-danger'
    elsif flash[:notice]
      hash[:message] = flash[:notice]
      hash[:style] = 'alert-info'
    elsif flash[:success]
      hash[:message] = flash[:success]
      hash[:style] = 'alert-success'
    end

    return hash
  end

  def display_flash(flash_content)
    flash_msg = "<div id=\"flash_message\" class=\"alert #{flash_content[:style]} alert-dismissible\">"\
      "<button type=\"button\" class=\"close\" data-dismiss=\"alert\">"\
        "<span aria-hidden=\"true\">&times;</span>"\
      "</button>"\
      "#{flash_content[:message]}"\
    "</div>"

    return html_safe(flash_msg)
  end

end

app/helpers/date_helper.rb
module DateHelper
  def format_date(date, format=:short)
    if date.present?
      l(date, format: format)
    else
      "No Date"
    end
  end
end

app/views/commits/index.html.erb
<h1>All Commits</h1>
<%= render partial: "shared/results", locals: { presenter: @presenter } =%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GitWebJlipson</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.0/themes/smoothness/jquery-ui.css" />
  <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.0/jquery-ui.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <%= render "shared/search" =%>
  <%= yield %>
</div>

</body>
</html>

app/views/search/search.html.erb
<%= link_to("Back to Commits", commits_path) %>
<%= render partial: "shared/results", locals: { presenter: @presenter } =%>

app/views/shared/_results.html.erb
<% flash_content = parse_flash(flash) %>
<% if flash_content.present? %>
  <%= display_flash(flash_content) %>
<% end %>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Date</th>
    <th>Subject</th>
    <th>Author</th>
    <th>Hash</th>
  </tr>
  </thead>
  <tbody>
    <% presenter.each do |commit| %>
    <tr>
      <td><%= commit.committed_at %></td>
      <td><%= html_safe(commit.message) %></td>
      <td><%= commit.author %></td>
      <td><%= commit.commit_hash %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/shared/_search.html.erb
<%= render partial: "shared/search_js" %>
<%= form_tag(search_path, method: 'get', class: 'form-inline', role: 'form') do %>
  <div class="form-group">
    <%= label_tag 'search','Search' %>
    <%= text_field_tag 'commit_hash', nil, placeholder: 'Enter commit hash...' %>
    <%= select_tag "author", options_from_collection_for_select(@authors, "name", "name"), prompt: "Select author" %>
    <%= text_field_tag 'committed_at', nil, placeholder: 'Click to select date...' %>
  </div>
  <%= submit_tag "Search", class: 'btn btn-primary' %>
<% end %>

app/views/shared/_search_js.html.erb
<script>
  $(document).ready( function() {
    $('#committed_at').datepicker({
        dateFormat: "yy-mm-dd",
        changeYear: true,
        yearRange: '1900:' + new Date().getFullYear(),
        maxDate: new Date(),
        showOn: "button",
        buttonImage: "assets/calendar.gif",
        buttonImageOnly: true,
        buttonText: "Select date"
    })
  });
</script>